# Chunking strategies configuration
# Defines how different types of content should be chunked for vectorization

default:
  chunk_size: 512            # Default token size for chunks
  chunk_overlap: 50          # Default overlap between chunks
  separator: "\n\n"          # Default chunk separator (paragraphs)
  include_metadata: true     # Always include metadata with chunks
  tokenizer: "cl100k_base"   # OpenAI tokenizer compatible with most embedding models

strategies:
  # Scripture specific chunking (Bible) - 3 Layer Approach
  verse_single:
    description: "Layer A: Single verse chunks for precise citations"
    chunk_type: "semantic_unit"
    chunk_unit: "verse"
    verses_per_chunk: 1
    include_context:
      book: true
      chapter: true
      testament: true
    metadata_fields:
      - book_name
      - chapter_number
      - verse_numbers
      - testament
      - layer
      - canonical_refs

  verse_pericope:
    description: "Layer B: Pericope chunks (3-7 verses with overlap) for main retrieval"
    chunk_type: "semantic_unit"
    chunk_unit: "pericope"
    window_size: 6               # 6 verses per window
    stride: 3                    # Move 3 verses for next window (50% overlap)
    min_verses: 3                # Minimum verses in a pericope
    max_verses: 7                # Maximum verses in a pericope
    special_handling:
      narrative_books: 
        window_size: 6
        stride: 3
      epistles:
        window_size: 4
        stride: 2
      poetry:
        window_size: 3
        stride: 2
    include_context:
      book: true
      chapter: true
      testament: true
    metadata_fields:
      - book_name
      - chapter_number
      - start_verse
      - end_verse
      - verse_numbers
      - testament
      - layer
      - window_info
      - canonical_refs
      - prev_ref
      - next_ref

  verse_chapter:
    description: "Layer C: Chapter-level chunks for broad context"
    chunk_type: "document_segment"
    chunk_unit: "chapter"
    max_tokens: 1600             # Split large chapters
    include_context:
      book: true
      testament: true
    metadata_fields:
      - book_name
      - chapter_number
      - testament
      - layer
      - verse_count

  # Book chunking (for Conflict of Ages books)
  paragraph:
    description: "Chunk by paragraphs with context"
    chunk_type: "text_window"    # Sliding window of text
    chunk_size: 750              # Target token count
    chunk_overlap: 100           # Overlap between chunks
    respect_boundaries:
      paragraph: true            # Don't split paragraphs if possible
      section: true              # Try to respect section boundaries
      chapter: false             # OK to split across chapters
    metadata_fields:
      - book_title
      - chapter_title
      - section_title
      - page_number

  # Chapter chunking (for longer content)
  chapter:
    description: "Chunk by chapters with minimal overlap"
    chunk_type: "document_segments"  # Each chunk is a document segment
    max_tokens: 1500            # Maximum tokens per chunk
    chapter_handling:
      short_chapters:
        strategy: "combine"      # Combine short chapters
        threshold: 300           # Threshold for "short" chapter (tokens)
      long_chapters:
        strategy: "split"        # Split long chapters
        target_size: 1000        # Target size for splits
    metadata_fields:
      - book_title
      - chapter_number
      - chapter_title
      - timestamp

# Special processors for specific content types
processors:
  scripture:
    - extract_book_chapter_verse  # Extract references
    - normalize_names             # Normalize character/place names
    - cross_reference_detector    # Detect and extract cross-references
    
  book:
    - extract_headings            # Extract section headings
    - page_number_tracker         # Track page numbers
    - footnote_processor          # Process footnotes
    - quote_extractor             # Extract and attribute quotes

# Vector storage settings
vector_storage:
  chroma_settings:
    collection_name: "theology"   # Collection name for ChromaDB
    embedding_function: "sentence-transformers"
    embedding_model: "all-MiniLM-L6-v2"  # Default embedding model
    distance_function: "cosine"
  
  document_metadata:
    common_fields:               # Fields common to all document types
      - source_id                # ID from sources.yaml
      - domain                   # Knowledge domain
      - chunk_strategy           # Strategy used for chunking
      - chunk_id                 # Unique ID for the chunk
      - creation_timestamp       # When the chunk was created
