# OSIS Canonical Reference System
# This file defines the canonical verse identification scheme for TinyOwl
# Based on Open Scripture Information Standard (OSIS) for cross-translation alignment

# Canonical Book Order and IDs
canonical_books:
  old_testament:
    - id: "Gen"
      full_name: "Genesis"
      chapter_count: 50
      verse_counts: [31, 25, 24, 26, 32, 22, 24, 22, 29, 32, 32, 18, 29, 23, 23, 20, 18, 24, 21, 16, 27, 33, 38, 18, 34, 24, 20, 67, 34, 35, 46, 22, 35, 43, 55, 32, 20, 31, 29, 43, 36, 30, 23, 23, 57, 38, 34, 34, 28, 34]
      aliases: ["Genesis", "Ge", "Gn"]
      
    - id: "Exod"
      full_name: "Exodus"
      chapter_count: 40
      verse_counts: [22, 25, 22, 31, 23, 30, 25, 32, 35, 29, 10, 51, 22, 31, 27, 36, 16, 27, 25, 26, 36, 31, 33, 18, 40, 37, 21, 43, 46, 38, 18, 35, 23, 35, 35, 38, 29, 31, 43, 38]
      aliases: ["Exodus", "Ex", "Exo"]
      
    - id: "Lev"
      full_name: "Leviticus"
      chapter_count: 27
      verse_counts: [17, 16, 17, 35, 19, 30, 38, 36, 24, 20, 47, 8, 59, 57, 33, 34, 16, 30, 37, 27, 24, 33, 44, 23, 55, 46, 34]
      aliases: ["Leviticus", "Le", "Lv"]
      
    - id: "Num"
      full_name: "Numbers"
      chapter_count: 36
      verse_counts: [54, 34, 51, 49, 31, 27, 89, 26, 23, 36, 35, 16, 33, 45, 41, 50, 13, 32, 22, 29, 35, 41, 30, 25, 18, 65, 23, 31, 40, 16, 54, 42, 56, 29, 34, 13]
      aliases: ["Numbers", "Nu", "Nm"]
      
    - id: "Deut"
      full_name: "Deuteronomy"
      chapter_count: 34
      verse_counts: [46, 37, 29, 49, 33, 25, 26, 20, 29, 22, 32, 32, 18, 29, 23, 22, 20, 22, 21, 20, 23, 30, 25, 22, 19, 19, 26, 68, 29, 20, 30, 52, 29, 12]
      aliases: ["Deuteronomy", "De", "Dt"]
      
    # Continue for all 39 OT books...
    # [Abbreviated for space - full list would include all books]
    
  new_testament:
    - id: "Matt"
      full_name: "Matthew"
      chapter_count: 28
      verse_counts: [25, 23, 17, 25, 48, 34, 29, 34, 38, 42, 30, 50, 58, 36, 39, 28, 27, 35, 30, 34, 46, 46, 39, 51, 46, 75, 66, 20]
      aliases: ["Matthew", "Mt", "Mat"]
      
    - id: "Mark"
      full_name: "Mark"
      chapter_count: 16
      verse_counts: [45, 28, 35, 41, 43, 56, 37, 38, 50, 52, 33, 44, 37, 72, 47, 20]
      aliases: ["Mark", "Mk", "Mr"]
      
    - id: "Luke"
      full_name: "Luke"
      chapter_count: 24
      verse_counts: [80, 52, 38, 44, 39, 49, 50, 56, 62, 42, 54, 59, 35, 35, 32, 31, 37, 43, 48, 47, 38, 71, 56, 53]
      aliases: ["Luke", "Lk", "Lu"]
      
    - id: "John"
      full_name: "John"
      chapter_count: 21
      verse_counts: [51, 25, 36, 54, 47, 71, 53, 59, 41, 42, 57, 50, 38, 31, 27, 33, 26, 40, 42, 31, 25]
      aliases: ["John", "Jn", "Joh"]
      
    # Continue for all 27 NT books...

# OSIS ID Format: Book.Chapter.Verse
# Examples:
# - Gen.01.001 (Genesis 1:1)
# - 1Sam.15.022 (1 Samuel 15:22)
# - Matt.05.001 (Matthew 5:1)
# - Rev.22.021 (Revelation 22:21)

# Book Alias Mapping for Text Normalization
book_aliases:
  "Genesis": "Gen"
  "Ge": "Gen"
  "Gn": "Gen"
  "1 Samuel": "1Sam"
  "1Samuel": "1Sam"
  "I Samuel": "1Sam"
  "1Sa": "1Sam"
  "First Samuel": "1Sam"
  "Matthew": "Matt"
  "Mt": "Matt"
  "Mat": "Matt"
  "Saint Matthew": "Matt"
  "St. Matthew": "Matt"
  # ... comprehensive mapping for all variations

# Verse Reference Patterns for Parsing
verse_patterns:
  # Standard formats
  - pattern: '(\w+)\s+(\d+):(\d+)(?:-(\d+))?'  # "John 3:16" or "John 3:16-17"
    groups: [book, chapter, verse_start, verse_end]
  
  - pattern: '(\w+)\s+(\d+):(\d+)-(\d+):(\d+)'  # "John 3:16-4:2" (cross-chapter)
    groups: [book, chapter_start, verse_start, chapter_end, verse_end]
  
  - pattern: '(\d+)\s+(\w+)\s+(\d+):(\d+)'  # "1 Samuel 15:22"
    groups: [book_num, book_name, chapter, verse]

# Normalization Rules
text_normalization:
  # Unicode normalization
  unicode_form: "NFKC"
  
  # Character replacements
  replacements:
    '"': '"'  # Smart quotes to straight
    '"': '"'
    ''': "'"
    ''': "'"
    '—': '-'  # Em dash to hyphen
    '–': '-'  # En dash to hyphen
    
  # Whitespace cleanup
  collapse_whitespace: true
  strip_leading_trailing: true
  
  # Remove ornamental elements
  remove_patterns:
    - '^\s*\d+\s*$'  # Standalone verse numbers on lines
    - '^Chapter \d+.*$'  # Chapter headers
    - '^Book of.*$'  # Book headers
    - '^\s*[★✦✧]\s*$'  # Ornamental symbols

# Validation Rules
validation:
  # Each translation must have these exact counts
  required_verse_totals:
    old_testament: 23145
    new_testament: 7957
    total: 31102
    
  # Books that must be present
  required_books: 66
  
  # Verse count tolerance (for variant traditions)
  verse_count_tolerance: 0  # Strict - no missing verses allowed
  
  # OSIS ID format validation
  osis_id_pattern: '^[A-Za-z0-9]+\.\d{2}\.\d{3}$'