# Theology Domain Source Configuration
# This file defines the sources for the theology domain

domain: theology
description: "Biblical texts and Conflict of Ages books"

sources:
  - id: bible_geneva
    title: "Geneva Bible (1560)"
    type: scripture
    author: "Various"
    year: 1560
    path: "domains/theology/raw/Geneva_Bible_1560.txt"
    language: "english"
    description: "The Geneva Bible, one of the most historically significant translations of the Bible"
    chunking_strategy: "verse"

  - id: bible_kjv
    title: "King James Version Bible"
    type: scripture
    author: "Various"
    year: 1611
    path: "domains/theology/raw/KJV.pdf"
    language: "english"
    description: "The King James Version of the Bible"
    structure:
      has_chapters: true
      has_verses: true
      book_names:
        - Genesis
        - Exodus
        # ... other books would be listed
        - Revelation
    metadata:
      testament_split: 
        old: ["Genesis", "Exodus", ... "Malachi"]  # Define actual books when implementing
        new: ["Matthew", "Mark", ... "Revelation"] # Define actual books when implementing
    chunking_strategy: "verse"

  - id: bible_nkjv
    title: "New King James Version Bible"
    type: scripture
    author: "Various"
    year: 1982
    path: "domains/theology/raw/Holy_Bible_NKJV.pdf"
    language: "english"
    description: "New King James Version - modern revision of the KJV"
    chunking_strategy: "verse"

  - id: bible_niv
    title: "New International Version Bible"
    type: scripture
    author: "Various"
    year: 1978
    path: "domains/theology/raw/Holy_Bible_NIV.pdf"
    language: "english"
    description: "New International Version - popular balanced translation"
    chunking_strategy: "verse"

  - id: bible_esv
    title: "English Standard Version Bible"
    type: scripture
    author: "Various"
    year: 2001
    path: "domains/theology/raw/Holy_Bible_ESV.pdf"
    language: "english"
    description: "English Standard Version - formal equivalence translation"
    chunking_strategy: "verse"

  - id: bible_nlt
    title: "New Living Translation Bible"
    type: scripture
    author: "Various"
    year: 1996
    path: "domains/theology/raw/Holy_Bible_NLT.pdf"
    language: "english"
    description: "New Living Translation - dynamic equivalence translation"
    chunking_strategy: "verse"

  - id: bible_geneva
    title: "Geneva Bible 1560"
    type: scripture
    author: "Various"
    year: 1560
    path: "domains/theology/raw/Geneva_Bible_1560.txt"
    language: "english"
    description: "Geneva Bible - historic Protestant translation"
    chunking_strategy: "verse"

  - id: bible_clear_word
    title: "Clear Word Bible"
    type: scripture
    author: "Jack Blanco"
    year: 1994
    path: "domains/theology/raw/Holy_Bible_Clear_Word.pdf"
    language: "english"
    description: "Clear Word - paraphrased interpretive version"
    chunking_strategy: "verse"

  - id: coa_patriarchs_prophets
    title: "Patriarchs and Prophets"
    type: book
    author: "Ellen G. White"
    year: 1890
    path: "domains/theology/raw/PatriarchsAndProphets.pdf"
    language: "english"
    description: "Covers Biblical history from creation to the end of David's reign"
    structure:
      has_chapters: true
      has_verses: false
    metadata:
      time_period: "Creation to end of David's reign"
      related_bible_books: ["Genesis", "Exodus", "Numbers", "Joshua", "Judges", "Ruth", "1 Samuel", "2 Samuel"]
    chunking_strategy: "paragraph"

  - id: coa_prophets_kings
    title: "Prophets and Kings"
    type: book
    author: "Ellen G. White"
    year: 1917
    path: "domains/theology/raw/ProphetsAndKings.pdf"
    language: "english"
    description: "Covers Biblical history from Solomon to Malachi"
    structure:
      has_chapters: true
      has_verses: false
    metadata:
      time_period: "Solomon to Malachi"
      related_bible_books: ["1 Kings", "2 Kings", "1 Chronicles", "2 Chronicles", "Ezra", "Nehemiah", "Esther", "Job", "Psalms", "Proverbs", "Ecclesiastes", "Song of Solomon", "Isaiah", "Jeremiah", "Lamentations", "Ezekiel", "Daniel", "Hosea", "Joel", "Amos", "Obadiah", "Jonah", "Micah", "Nahum", "Habakkuk", "Zephaniah", "Haggai", "Zechariah", "Malachi"]
    chunking_strategy: "paragraph"

  - id: coa_desire_of_ages
    title: "The Desire of Ages"
    type: book
    author: "Ellen G. White"
    year: 1898
    path: "domains/theology/raw/DesireofAges.pdf"
    language: "english"
    description: "Covers the life and ministry of Jesus Christ"
    structure:
      has_chapters: true
      has_verses: false
    metadata:
      time_period: "Life of Christ"
      related_bible_books: ["Matthew", "Mark", "Luke", "John"]
    chunking_strategy: "paragraph"

  - id: coa_acts_of_apostles
    title: "The Acts of the Apostles"
    type: book
    author: "Ellen G. White"
    year: 1911
    path: "domains/theology/raw/ActsofTheApostles.pdf"
    language: "english"
    description: "Covers the history of the early Christian church"
    structure:
      has_chapters: true
      has_verses: false
    metadata:
      time_period: "Early Christian Church"
      related_bible_books: ["Acts", "Romans", "1 Corinthians", "2 Corinthians", "Galatians", "Ephesians", "Philippians", "Colossians", "1 Thessalonians", "2 Thessalonians", "1 Timothy", "2 Timothy", "Titus", "Philemon", "Hebrews", "James", "1 Peter", "2 Peter", "1 John", "2 John", "3 John", "Jude"]
    chunking_strategy: "paragraph"

  - id: coa_great_controversy
    title: "The Great Controversy"
    type: book
    author: "Ellen G. White"
    year: 1911
    path: "domains/theology/raw/The Great Controversy.pdf"
    language: "english"
    description: "Covers Christian history from the destruction of Jerusalem to the end of sin"
    structure:
      has_chapters: true
      has_verses: false
    metadata:
      time_period: "Destruction of Jerusalem to End of Sin"
      related_bible_books: ["Daniel", "Revelation"]
    chunking_strategy: "paragraph"
